threat_dragon_version: "2.2.0"
title: "My threat modeling"
owner: "me"
description: "This is my description"
diagrams:
  - name: A2_Child_Data_Flow
    parent: A1_Diagram1
    nodes:
      - MyProcess
      - RabbitMq
      - Prometheus
