threatDragonVersion: "2.2.0" # Version of OWASP Threat Dragon to use
title: "My threat modeling"
owner: "me"
description: "This is my description"
trustBoundaries: # Trust boundaries used in diagrams
  - name: Enablers
    description: "Enabler services provided"
    limitOfAccess: "Operational" # Limit of access Operational or Administration
    levelOfAuthorization: "Application data"
  - name: Enablers2
    description: "Enabler services provided"
    limitOfAccess: "Operational"
    levelOfAuthorization: "Application data"
assets: # Assets used in node flow
  - name: OpenApi
    description: "OpenApi messages"
diagrams: # Childs diagrams
  - name: A2_Child_Data_Flow
    parent: A1_Diagram1 # title field in the parent diagram
    description: ""
    nodes: # list of node to display in child
      - MyProcess
      - RabbitMq
      - Prometheus
      - Minio
  - name: B2_Child_Data_Flow
    parent: B1_Diagram2
    description: ""
    nodes:
      - MyProcess
      - RabbitMq2
