name: Docker

on:
  push:
    branches:
      - feature/docker-publish
    # tags: [ '*' ]

env:
  REGISTRY: docker.io
  # <account>/<repo>
  IMAGE_NAME: threatdragongenerator/threat-dragon-generator

 # ${{ env.IMAGE_NAME }}:${{  github.ref_name }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: image_delivery
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
